<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="system" ignored="0" tests="8" failures="3" timestamp="2021-08-14T12:45:27 IST" time="7.416" errors="0">
  <testcase name="postemployeedetails" time="3.326" classname="CreateEmployee"/>
  <testcase name="statusCode" time="0.008" classname="CreateEmployee">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at CreateEmployee.statusCode(CreateEmployee.java:35)
at java.util.ArrayList.forEach(ArrayList.java:1234)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- statusCode -->
  <testcase name="checkResponseBody" time="0.034" classname="GetEmployee"/>
  <testcase name="getemployeedetails" time="1.371" classname="GetEmployee"/>
  <testcase name="statusCode" time="0.004" classname="GetEmployee"/>
  <testcase name="statusLine" time="0.003" classname="GetEmployee"/>
  <testcase name="deleteemployeedata" time="1.486" classname="DeleteEmployee">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at DeleteEmployee.deleteemployeedata(DeleteEmployee.java:21)
at java.util.ArrayList.forEach(ArrayList.java:1234)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 33 more
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- deleteemployeedata -->
  <testcase name="statusCode" time="0.003" classname="DeleteEmployee">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at DeleteEmployee.statusCode(DeleteEmployee.java:31)
at java.util.ArrayList.forEach(ArrayList.java:1234)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- statusCode -->
</testsuite>
